########################################################################
# 
#   each item:
# 
#   [
#     glyph,
#     left_end_type,
#     up_end_type,
#     right_end_type,
#     down_end_type,
#     heart_type,
#     suitable fonts
#   ]
# 
########################################################################

Glyphs = [
  [' ', BLANK,   BLANK,   BLANK,   BLANK,   PLAIN,  ['Menlo','Courrier']], 
  ['╴', REGULAR, BLANK,   BLANK,   BLANK,   PLAIN,  ['Menlo','Courrier']], 
  ['╸', BOLD,    BLANK,   BLANK,   BLANK,   PLAIN,  ['Menlo']], 
  ['╵', BLANK,   REGULAR, BLANK,   BLANK,   PLAIN,  ['Menlo','Courrier']], 
  ['╹', BLANK,   BOLD,    BLANK,   BLANK,   PLAIN,  ['Menlo']], 
  ['╶', BLANK,   BLANK,   REGULAR, BLANK,   PLAIN,  ['Menlo','Courrier']], 
  ['╺', BLANK,   BLANK,   BOLD,    BLANK,   PLAIN,  ['Menlo']], 
  ['╷', BLANK,   BLANK,   BLANK,   REGULAR, PLAIN,  ['Menlo','Courrier']], 
  ['╻', BLANK,   BLANK,   BLANK,   BOLD,    PLAIN,  ['Menlo']], 
  ['┘', REGULAR, REGULAR, BLANK,   BLANK,   PLAIN,  ['Menlo','Courrier']], 
  ['╯', REGULAR, REGULAR, BLANK,   BLANK,   ROUND,  ['Menlo']], 
  ['┛', BOLD,    BOLD,    BLANK,   BLANK,   PLAIN,  ['Menlo']], 
  ['┙', BOLD,    REGULAR, BLANK,   BLANK,   PLAIN,  ['Menlo']], 
  ['┚', REGULAR, BOLD,    BLANK,   BLANK,   PLAIN,  ['Menlo']], 
  ['─', REGULAR, BLANK,   REGULAR, BLANK,   PLAIN,  ['Menlo','Courrier']],
  ['┄', REGULAR, BLANK,   REGULAR, BLANK,   DASHED, ['Menlo']],
  ['►', REGULAR, BLANK,   BLANK,   BLANK,   ARROW,  ['Menlo']],
  ['>', REGULAR, BLANK,   BLANK,   BLANK,   ARROW,  ['Courrier']],
  ['◄', BLANK,   BLANK,   REGULAR, BLANK,   ARROW,  ['Menlo']],
  ['<', BLANK,   BLANK,   REGULAR, BLANK,   ARROW,  ['Courrier']],
  ['━', BOLD,    BLANK,   BOLD,    BLANK,   PLAIN,  ['Menlo']], 
  ['┅', BOLD,    BLANK,   BOLD,    BLANK,   DASHED, ['Menlo']],
  ['▶', BOLD,    BLANK,   BLANK,   BLANK,   ARROW,  ['Menlo']],
  ['◀', BLANK,   BLANK,   BOLD,    BLANK,   ARROW,  ['Menlo']], 
  ['╾', BOLD,    BLANK,   REGULAR, BLANK,   PLAIN,  ['Menlo']], 
  ['╼', REGULAR, BLANK,   BOLD,    BLANK,   PLAIN,  ['Menlo']], 
  ['┐', REGULAR, BLANK,   BLANK,   REGULAR, PLAIN,  ['Menlo','Courrier']], 
  ['╮', REGULAR, BLANK,   BLANK,   REGULAR, ROUND,  ['Menlo']], 
  ['┓', BOLD,    BLANK,   BLANK,   BOLD,    PLAIN,  ['Menlo']], 
  ['┑', BOLD,    BLANK,   BLANK,   REGULAR, PLAIN,  ['Menlo']], 
  ['┒', REGULAR, BLANK,   BLANK,   BOLD,    PLAIN,  ['Menlo']], 
  ['└', BLANK,   REGULAR, REGULAR, BLANK,   PLAIN,  ['Menlo','Courrier']], 
  ['╰', BLANK,   REGULAR, REGULAR, BLANK,   ROUND,  ['Menlo']], 
  ['┗', BLANK,   BOLD,    BOLD,    BLANK,   PLAIN,  ['Menlo']], 
  ['┖', BLANK,   BOLD,    REGULAR, BLANK,   PLAIN,  ['Menlo']], 
  ['┕', BLANK,   REGULAR, BOLD,    BLANK,   PLAIN,  ['Menlo']], 
  ['│', BLANK,   REGULAR, BLANK,   REGULAR, PLAIN,  ['Menlo','Courrier']],
  ['┊', BLANK,   REGULAR, BLANK,   REGULAR, DASHED, ['Menlo']], 
  ['⍒', BLANK,   REGULAR, BLANK,   BLANK,   ARROW,  ['Menlo']],
  ['V', BLANK,   REGULAR, BLANK,   BLANK,   ARROW,  ['Courrier']], 
  ['⍋', BLANK,   BLANK,   BLANK,   REGULAR, ARROW,  ['Menlo']], 
  ['Λ', BLANK,   BLANK,   BLANK,   REGULAR, ARROW,  ['Courrier']], 
  ['┃', BLANK,   BOLD,    BLANK,   BOLD,    PLAIN,  ['Menlo']], 
  ['┋', BLANK,   BOLD,    BLANK,   BOLD,    DASHED, ['Menlo']], 
  ['▼', BLANK,   BOLD,    BLANK,   BLANK,   ARROW,  ['Menlo']],
  ['▲', BLANK,   BLANK,   BLANK,   BOLD,    ARROW,  ['Menlo']],
  ['╿', BLANK,   BOLD,    BLANK,   REGULAR, PLAIN,  ['Menlo']],
  ['╽', BLANK,   REGULAR, BLANK,   BOLD,    PLAIN,  ['Menlo']],
  ['┌', BLANK,   BLANK,   REGULAR, REGULAR, PLAIN,  ['Menlo','Courrier']],
  ['╭', BLANK,   BLANK,   REGULAR, REGULAR, ROUND,  ['Menlo']],
  ['┏', BLANK,   BLANK,   BOLD,    BOLD,    PLAIN,  ['Menlo']],
  ['┍', BLANK,   BLANK,   BOLD,    REGULAR, PLAIN,  ['Menlo']],
  ['┎', BLANK,   BLANK,   REGULAR, BOLD,    PLAIN,  ['Menlo']],
  ['┴', REGULAR, REGULAR, REGULAR, BLANK,   PLAIN,  ['Menlo','Courrier']],
  ['┻', BOLD,    BOLD,    BOLD,    BLANK,   PLAIN,  ['Menlo']],
  ['┵', BOLD,    REGULAR, REGULAR, BLANK,   PLAIN,  ['Menlo']],
  ['┸', REGULAR, BOLD,    REGULAR, BLANK,   PLAIN,  ['Menlo']],
  ['┶', REGULAR, REGULAR, BOLD,    BLANK,   PLAIN,  ['Menlo']],
  ['┺', REGULAR, BOLD,    BOLD,    BLANK,   PLAIN,  ['Menlo']],
  ['┷', BOLD,    REGULAR, BOLD,    BLANK,   PLAIN,  ['Menlo']],
  ['┹', BOLD,    BOLD,    REGULAR, BLANK,   PLAIN,  ['Menlo']],
  ['┤', REGULAR, REGULAR, BLANK,   REGULAR, PLAIN,  ['Menlo','Courrier']],
  ['┫', BOLD,    BOLD,    BLANK,   BOLD,    PLAIN,  ['Menlo']],
  ['┥', BOLD,    REGULAR, BLANK,   REGULAR, PLAIN,  ['Menlo']],
  ['┦', REGULAR, BOLD,    BLANK,   REGULAR, PLAIN,  ['Menlo']],
  ['┧', REGULAR, REGULAR, BLANK,   BOLD,    PLAIN,  ['Menlo']],
  ['┨', REGULAR, BOLD,    BLANK,   BOLD,    PLAIN,  ['Menlo']],
  ['┪', BOLD,    REGULAR, BLANK,   BOLD,    PLAIN,  ['Menlo']],
  ['┩', BOLD,    BOLD,    BLANK,   REGULAR, PLAIN,  ['Menlo']], 
  ['┬', REGULAR, BLANK,   REGULAR, REGULAR, PLAIN,  ['Menlo','Courrier']], 
  ['┳', BOLD,    BLANK,   BOLD,    BOLD,    PLAIN,  ['Menlo']], 
  ['┭', BOLD,    BLANK,   REGULAR, REGULAR, PLAIN,  ['Menlo']], 
  ['┮', REGULAR, BLANK,   BOLD,    REGULAR, PLAIN,  ['Menlo']], 
  ['┰', REGULAR, BLANK,   REGULAR, BOLD,    PLAIN,  ['Menlo']], 
  ['┲', REGULAR, BLANK,   BOLD,    BOLD,    PLAIN,  ['Menlo']], 
  ['┱', BOLD,    BLANK,   REGULAR, BOLD,    PLAIN,  ['Menlo']], 
  ['┯', BOLD,    BLANK,   BOLD,    REGULAR, PLAIN,  ['Menlo']], 
  ['├', BLANK,   REGULAR, REGULAR, REGULAR, PLAIN,  ['Menlo','Courrier']], 
  ['┣', BLANK,   BOLD,    BOLD,    BOLD,    PLAIN,  ['Menlo']], 
  ['┞', BLANK,   BOLD,    REGULAR, REGULAR, PLAIN,  ['Menlo']], 
  ['┝', BLANK,   REGULAR, BOLD,    REGULAR, PLAIN,  ['Menlo']], 
  ['┟', BLANK,   REGULAR, REGULAR, BOLD,    PLAIN,  ['Menlo']], 
  ['┢', BLANK,   REGULAR, BOLD,    BOLD,    PLAIN,  ['Menlo']], 
  ['┠', BLANK,   BOLD,    REGULAR, BOLD,    PLAIN,  ['Menlo']], 
  ['┡', BLANK,   BOLD,    BOLD,    REGULAR, PLAIN,  ['Menlo']], 
  ['┼', REGULAR, REGULAR, REGULAR, REGULAR, PLAIN,  ['Menlo','Courrier']], 
  ['╋', BOLD,    BOLD,    BOLD,    BOLD,    PLAIN,  ['Menlo']], 
  ['┽', BOLD,    REGULAR, REGULAR, REGULAR, PLAIN,  ['Menlo']], 
  ['╀', REGULAR, BOLD,    REGULAR, REGULAR, PLAIN,  ['Menlo']], 
  ['┾', REGULAR, REGULAR, BOLD,    REGULAR, PLAIN,  ['Menlo']], 
  ['╁', REGULAR, REGULAR, REGULAR, BOLD,    PLAIN,  ['Menlo']], 
  ['╊', REGULAR, BOLD,    BOLD,    BOLD,    PLAIN,  ['Menlo']], 
  ['╈', BOLD,    REGULAR, BOLD,    BOLD,    PLAIN,  ['Menlo']], 
  ['╉', BOLD,    BOLD,    REGULAR, BOLD,    PLAIN,  ['Menlo']], 
  ['╇', BOLD,    BOLD,    BOLD,    REGULAR, PLAIN,  ['Menlo']], 
  ['╂', REGULAR, BOLD,    REGULAR, BOLD,    PLAIN,  ['Menlo']], 
  ['┿', BOLD,    REGULAR, BOLD,    REGULAR, PLAIN,  ['Menlo']], 
  ['╃', BOLD,    BOLD,    REGULAR, REGULAR, PLAIN,  ['Menlo']], 
  ['╄', REGULAR, BOLD,    BOLD,    REGULAR, PLAIN,  ['Menlo']], 
  ['╆', REGULAR, REGULAR, BOLD,    BOLD,    PLAIN,  ['Menlo']], 
  ['╅', BOLD,    REGULAR, REGULAR, BOLD,    PLAIN,  ['Menlo']], 
  ['═', DOUBLE,  BLANK,   DOUBLE,  BLANK,   PLAIN,  ['Menlo']], 
  ['▷', DOUBLE,  BLANK,   BLANK,   BLANK,   ARROW,  ['Menlo']],
  ['◁', BLANK,   BLANK,   DOUBLE,  BLANK,   ARROW,  ['Menlo']], 
  ['║', BLANK,   DOUBLE,  BLANK,   DOUBLE,  PLAIN,  ['Menlo']], 
  ['▽', BLANK,   DOUBLE,  BLANK,   BLANK,   ARROW,  ['Menlo']],
  ['△', BLANK,   BLANK,   BLANK,   DOUBLE,  ARROW,  ['Menlo']], 
  ['╝', DOUBLE,  DOUBLE,  BLANK,   BLANK,   PLAIN,  ['Menlo']], 
  ['╚', BLANK,   DOUBLE,  DOUBLE,  BLANK,   PLAIN,  ['Menlo']], 
  ['╔', BLANK,   BLANK,   DOUBLE,  DOUBLE,  PLAIN,  ['Menlo']], 
  ['╗', DOUBLE,  BLANK,   BLANK,   DOUBLE,  PLAIN,  ['Menlo']], 
  ['╜', REGULAR, DOUBLE,  BLANK,   BLANK,   PLAIN,  ['Menlo']], 
  ['╘', BLANK,   REGULAR, DOUBLE,  BLANK,   PLAIN,  ['Menlo']], 
  ['╓', BLANK,   BLANK,   REGULAR, DOUBLE,  PLAIN,  ['Menlo']], 
  ['╕', DOUBLE,  BLANK,   BLANK,   REGULAR, PLAIN,  ['Menlo']], 
  ['╛', DOUBLE,  REGULAR, BLANK,   BLANK,   PLAIN,  ['Menlo']], 
  ['╙', BLANK,   DOUBLE,  REGULAR, BLANK,   PLAIN,  ['Menlo']], 
  ['╒', BLANK,   BLANK,   DOUBLE,  REGULAR, PLAIN,  ['Menlo']], 
  ['╖', REGULAR, BLANK,   BLANK,   DOUBLE,  PLAIN,  ['Menlo']], 
  ['╩', DOUBLE,  DOUBLE,  DOUBLE,  BLANK,   PLAIN,  ['Menlo']], 
  ['╠', BLANK,   DOUBLE,  DOUBLE,  DOUBLE,  PLAIN,  ['Menlo']], 
  ['╦', DOUBLE,  BLANK,   DOUBLE,  DOUBLE,  PLAIN,  ['Menlo']], 
  ['╣', DOUBLE,  DOUBLE,  BLANK,   DOUBLE,  PLAIN,  ['Menlo']], 
  ['╨', REGULAR, DOUBLE,  REGULAR, BLANK,   PLAIN,  ['Menlo']], 
  ['╞', BLANK,   REGULAR, DOUBLE,  REGULAR, PLAIN,  ['Menlo']], 
  ['╥', REGULAR, BLANK,   REGULAR, DOUBLE,  PLAIN,  ['Menlo']], 
  ['╡', DOUBLE,  REGULAR, BLANK,   REGULAR, PLAIN,  ['Menlo']], 
  ['╧', DOUBLE,  REGULAR, DOUBLE,  BLANK,   PLAIN,  ['Menlo']], 
  ['╟', BLANK,   DOUBLE,  REGULAR, DOUBLE,  PLAIN,  ['Menlo']], 
  ['╤', DOUBLE,  BLANK,   DOUBLE,  REGULAR, PLAIN,  ['Menlo']], 
  ['╢', REGULAR, DOUBLE,  BLANK,   DOUBLE,  PLAIN,  ['Menlo']], 
  ['╬', DOUBLE,  DOUBLE,  DOUBLE,  DOUBLE,  PLAIN,  ['Menlo']], 
  ['╪', DOUBLE,  REGULAR, DOUBLE,  REGULAR, PLAIN,  ['Menlo']], 
  ['╫', REGULAR, DOUBLE,  REGULAR, DOUBLE,  PLAIN,  ['Menlo']], 
]